<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGCM.Domain\SGCM.Domain.csproj" />
    <ProjectReference Include="..\SGCM.Data\SGCM.Data.csproj" />
  </ItemGroup>

</Project>
